GET http://localhost:5000/api/users/details
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE


###
POST http://localhost:5000/api/users/create 
Content-Type: application/json
Accept: application/json

{
    "name":"Kishor Mainali",
    "email":"mainali152kishor3@gmail.com",
    "password":"password"
}

###
GET http://localhost:5000/api/users/
Content-Type: application/json
Accept: application/json


###
DELETE  http://localhost:5000/api/users/delete/5fe1bfcc19c5193d0813af4b
Content-Type: application/json
Accept: application/json


###
PUT http://localhost:5000/api/users/update/5fe1bfcc19c5193d0813af4b
Content-Type: application/json
Accept: application/json

{
    "name":"Kishor Mainali",
    "password":"password"
}

###
POST http://localhost:5000/api/users/signin
Content-Type: application/json
Accept: application/json

{
    "email":"mainali152kishor@gmail.com",
    "password":"password"
}


###
POST http://localhost:5000/api/v1/posts/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE


{
    "title":"Test Title2",
    "body":"Pariatur ea consequat ad nisi do nostrud amet ut duis deserunt aute fugiat. Quis amet Lorem tempor anim. Exercitation adipisicing sint ea proident. Occaecat excepteur adipisicing consequat cillum qui aliquip consequat veniam ex reprehenderit anim consectetur dolore."
}


###
GET http://localhost:5000/api/v1/posts/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE


###
PATCH  http://localhost:5000/api/v1/posts/update/5fe1d9676cba594527b1af99
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE
 
 {
    "title":"Test Title updated",
    "body":"Pariatur ea consequat ad nisi do nostrud amet ut duis deserunt aute fugiat. Quis amet Lorem tempor anim. Exercitation adipisicing sint ea proident. Occaecat excepteur adipisicing consequat cillum qui aliquip consequat veniam ex reprehenderit anim consectetur dolore."
}


###
DELETE   http://localhost:5000/api/v1/posts/delete/5fe1d9796cba594527b1af9a
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE
 
 

###
GET   http://localhost:5000/api/v1/posts/5fe1e813bb025749cd1dec17
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmUxZDk1YjZjYmE1OTQ1MjdiMWFmOTgiLCJ1c2VybmFtZSI6Iktpc2hvciBNYWluYWxpIiwiaWF0IjoxNjA4NjM5MTkxLCJleHAiOjE2MDg3MjU1OTF9.alK9pWJ-MkQaWgXbbRn6ynhOkoG0kfc5d5gYwZ8yKKE
